server:
  port: 3333

spring:
  application:
    name: app-be

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:android_db}?useSSL=true&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: "${DB_PASSWORD:24102004}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        #        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
    baseline-on-migrate: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:B1AFoI/GoJbfavxVh8G6G3GLZz/du9Oco2GGlhDGxQE=}
      expiration_seconds: ${JWT_EXPIRATION:28800}
    default_password: ${DEFAULT_PASSWORD:12345678}

logging:
  level:
    flyway: DEBUG

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dsy6qo8ag}
  api_key: ${CLOUDINARY_API_KEY:159817786689414}
  api_secret: ${CLOUDINARY_API_SECRET:CtYu6RwalX2vAaL-SIyFRcTxh1o}